### ISSUE TITLE
Apply BEM to Barcodes's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Barcodes#6]
This app contains globally applied CSS rules in stylesheets: 

- https://github.com/StarcounterSamples/Barcodes/blob/3d92f19db54c06117cc7e0557d042012ce6670c8/src/Barcodes/wwwroot/Barcodes/css/barcodes.css
- https://github.com/StarcounterSamples/Barcodes/blob/1fcb81ec8e0e45d0a8ac6990d8849faf89b343a0/src/Barcodes/wwwroot/Barcodes/css/standalone.css

It also contains inline CSS in HTML templates: 

- https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/wwwroot/Barcodes/viewmodels/BarcodesPage.html

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article **http://starcounter.io/guides/web/avoiding-css-conflicts/**

**Comment by warpech** [comment]
@aloscha will have more information in case you need help with this.

**Comment by aloscha** [comment]
@warpech we have problem with naming class, which is come from Bootstrap like `.btn` or `form-group`.
Maybe better solution is to inherit from that class and provide only bem class.
I mean by @extend. Example here: http://stackoverflow.com/questions/9560170/including-another-class-in-scss

What do you think? (I know that is scss, but I think is't not a problem, in the result we will use only bem class names)?

**Comment by ubbeK** [comment]
I like the idea but I wonder how much we gain by doing this, the Bootstrap API should be stable by now. If we really want all of our styles to be BEM:inized with all its advantages, we should definitely use it but it adds another layer to the code which makes it more abstract.

**Comment by warpech** [comment]
There is no way we can extend it with SCSS. The file `bootstrap.css` comes from the outside of Barcodes up, so it must be treated as read-only.

Why don't we just do it like `<button class="btn barcodes-button">`?

**Comment by warpech** [comment]
This is fixed by https://github.com/StarcounterSamples/Barcodes/pull/8
